name: "打开设置并进入蓝牙页面"
version: "1.0"
description: "启动设置应用，找到蓝牙选项并进入蓝牙设置页面"

variables:
  settings_package: "com.android.settings/.Settings"
  bluetooth_keyword: "蓝牙"

actions:
  - name: "启动设置应用"
    type: "start_app"
    params:
      package: "{{settings_package}}"
  
  - name: "等待设置应用启动"
    type: "wait"
    params:
      seconds: 3
  
  - name: "截图并OCR识别"
    type: "ocr"
  
  - name: "查找并点击蓝牙设置"
    type: "click_text"
    params:
      text: "{{bluetooth_keyword}}"
  
  - name: "等待蓝牙页面加载"
    type: "wait"
    params:
      seconds: 2
  
  - name: "截图确认蓝牙页面"
    type: "ocr"